# Generated by Django 5.2.6 on 2025-09-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
